INSERT INTO CAL_LOG (id, x, y, result) VALUES (1, 1, 2, 3)
INSERT INTO CAL_LOG (id, x, y, result) VALUES (2, 2, 2, 4)
INSERT INTO CAL_LOG (id, x, y, result) VALUES (3, 3, 2, 5)
INSERT INTO CAL_LOG (id, x, y, result) VALUES (4, 4, 2, 2)
INSERT INTO CAL_LOG (id, x, y, result) VALUES (5, 5, 2, 3)
INSERT INTO CAL_LOG (id, x, y, result) VALUES (6, 6, 2, 3)
INSERT INTO CAL_LOG (id, x, y, result) VALUES (7, 7, 2, 5)
